[workspace]
members = ["ruskcov", "inject", "inject-types"]

[profile.release]
lto = true

[patch.crates-io]
nix = { git = "https://github.com/nix-rust/nix.git" }
findshlibs = { path = "../findshlibs" }
