[package]
name = "ruskcov-inject"
version = "0.1.0"
build = "build.rs"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1"
libc = "0.2"
inject-types = { path = "../inject-types" }
bincode = "1.2"
itertools = "0.8"

[build-dependencies]
cc = "1.0"
